# Generated by Django 3.2.18 on 2023-03-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='actions',
        ),
    ]
